version: '3'

services:
  cache:
    build: ./springboot-cache-demo
    ports:
      - 8001:8001
    environment:
      DB_HOST: ${MYSQL_CONTAINER_NAME}
      REDIS_HOST: ${REDIS_CONTAINER_NAME}
    container_name: cache-demo
    networks:
      - mysql
      - redis

networks:
  redis:
    external:
      name: redis
  mysql:
    external:
      name: mysql