version: '3'

services:
  cache:
    build: ./springboot-cache-demo
    ports:
      - 8001:8001
    environment:
      DB_HOST: ${MYSQL_CONTAINER_NAME}
      REDIS_HOST: ${REDIS_CONTAINER_NAME}
    container_name: cache-demo
    networks:
      - mysql
      - redis

# docker network create redis
# docker network connect REDIS_NETWORK_ID REDIS_CONTAINER_NAME
# docker network create mysql
# docker network connect MYSQL_NETWORK_ID MYSQL_CONTAINER_NAME
networks:
  redis:
    external:
      name: redis
  mysql:
    external:
      name: mysql