spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:spring_cache}
    password: ${DB_PASSWORD:123456}
    username: ${DB_USERNAME:root}
  jpa:
    show-sql: true
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
server:
  port: ${PORT:8001}

logging:
  level:
#    root: trace
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

