spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache
    password: 123456
    username: root
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
server:
  port: 8001

logging:
  level:
#    root: trace
    org:
      hibernate:
        type: trace
