server:
  port: 8004

spring:
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    properties:
      mail:
        smtp:
          ssl:
            enable: true

